import type { SupportedLocale } from "@print-cess/i18n";

export type ProScanCopy = {
  liveCamera: string;
  cameraStarting: string;
  cameraDenied: string;
  cameraFallback: string;
  closeCamera: string;
  manualCapture: string;
  autoCaptureOn: string;
  autoCaptureOff: string;
  holdSteady: string;
  moveCloser: string;
  moreLight: string;
  tooBright: string;
  reduceGlare: string;
  blurry: string;
  ready: string;
  quality: string;
  searchablePdf: string;
  searchableHelp: string;
  ocrPreparing: string;
  ocrRecognizing: string;
  ocrFailed: string;
  ocrNetwork: string;
  imageOnlyPdf: string;
  privacyOcr: string;
};

const en: ProScanCopy = {
  liveCamera: "Smart camera",
  cameraStarting: "Starting camera…",
  cameraDenied: "Camera access is unavailable.",
  cameraFallback: "Use the device camera instead",
  closeCamera: "Close camera",
  manualCapture: "Capture now",
  autoCaptureOn: "Auto capture on",
  autoCaptureOff: "Auto capture off",
  holdSteady: "Hold steady",
  moveCloser: "Move closer",
  moreLight: "Add more light",
  tooBright: "Reduce the light",
  reduceGlare: "Tilt slightly to reduce glare",
  blurry: "Hold still for a sharper scan",
  ready: "Ready to capture",
  quality: "Capture quality",
  searchablePdf: "Searchable PDF (OCR)",
  searchableHelp: "Recognize text on this device and add an invisible searchable layer.",
  ocrPreparing: "Preparing on-device OCR…",
  ocrRecognizing: "Recognizing text…",
  ocrFailed: "Text recognition failed. The scan is still safe on this device.",
  ocrNetwork: "The OCR engine and language model are downloaded when first used.",
  imageOnlyPdf: "Create image-only PDF",
  privacyOcr: "Your page images are not uploaded for OCR.",
};

const ko: ProScanCopy = {
  liveCamera: "스마트 카메라",
  cameraStarting: "카메라를 준비하는 중…",
  cameraDenied: "카메라에 접근할 수 없습니다.",
  cameraFallback: "기기 카메라로 촬영",
  closeCamera: "카메라 닫기",
  manualCapture: "지금 촬영",
  autoCaptureOn: "자동 촬영 켜짐",
  autoCaptureOff: "자동 촬영 꺼짐",
  holdSteady: "잠시 고정해 주세요",
  moveCloser: "문서에 더 가까이 가세요",
  moreLight: "조명을 더 밝게 해주세요",
  tooBright: "조명을 조금 줄여주세요",
  reduceGlare: "빛 반사를 줄이도록 살짝 기울이세요",
  blurry: "선명하게 촬영되도록 고정해 주세요",
  ready: "촬영 준비 완료",
  quality: "촬영 품질",
  searchablePdf: "검색 가능한 PDF (OCR)",
  searchableHelp: "이 기기에서 글자를 인식해 PDF에 보이지 않는 검색용 텍스트를 넣습니다.",
  ocrPreparing: "기기 내 OCR을 준비하는 중…",
  ocrRecognizing: "글자를 인식하는 중…",
  ocrFailed: "글자 인식에 실패했습니다. 스캔 이미지는 이 기기에 그대로 안전하게 남아 있습니다.",
  ocrNetwork: "OCR 엔진과 언어 모델은 처음 사용할 때 다운로드됩니다.",
  imageOnlyPdf: "이미지 PDF로 만들기",
  privacyOcr: "OCR을 위해 문서 이미지를 서버로 업로드하지 않습니다.",
};

const zhCN: ProScanCopy = {
  liveCamera: "智能相机",
  cameraStarting: "正在启动相机…",
  cameraDenied: "无法使用相机。",
  cameraFallback: "改用设备相机",
  closeCamera: "关闭相机",
  manualCapture: "立即拍摄",
  autoCaptureOn: "自动拍摄已开启",
  autoCaptureOff: "自动拍摄已关闭",
  holdSteady: "请保持稳定",
  moveCloser: "请靠近文档",
  moreLight: "请增加光线",
  tooBright: "请降低光线",
  reduceGlare: "稍微倾斜以减少反光",
  blurry: "请保持不动以获得清晰扫描",
  ready: "可以拍摄",
  quality: "拍摄质量",
  searchablePdf: "可搜索 PDF (OCR)",
  searchableHelp: "在本设备识别文字，并添加不可见的可搜索文本层。",
  ocrPreparing: "正在准备设备端 OCR…",
  ocrRecognizing: "正在识别文字…",
  ocrFailed: "文字识别失败。扫描图像仍安全保留在本设备。",
  ocrNetwork: "首次使用时会下载 OCR 引擎和语言模型。",
  imageOnlyPdf: "创建纯图像 PDF",
  privacyOcr: "OCR 不会上传您的页面图像。",
};

const id: ProScanCopy = {
  liveCamera: "Kamera pintar",
  cameraStarting: "Menyiapkan kamera…",
  cameraDenied: "Akses kamera tidak tersedia.",
  cameraFallback: "Gunakan kamera perangkat",
  closeCamera: "Tutup kamera",
  manualCapture: "Ambil sekarang",
  autoCaptureOn: "Ambil otomatis aktif",
  autoCaptureOff: "Ambil otomatis nonaktif",
  holdSteady: "Tahan tetap",
  moveCloser: "Dekatkan ke dokumen",
  moreLight: "Tambahkan cahaya",
  tooBright: "Kurangi cahaya",
  reduceGlare: "Miringkan sedikit untuk mengurangi pantulan",
  blurry: "Tahan agar hasil lebih tajam",
  ready: "Siap mengambil",
  quality: "Kualitas tangkapan",
  searchablePdf: "PDF dapat dicari (OCR)",
  searchableHelp: "Kenali teks di perangkat ini dan tambahkan lapisan teks tersembunyi.",
  ocrPreparing: "Menyiapkan OCR di perangkat…",
  ocrRecognizing: "Mengenali teks…",
  ocrFailed: "Pengenalan teks gagal. Hasil pindai tetap aman di perangkat ini.",
  ocrNetwork: "Mesin OCR dan model bahasa diunduh saat pertama digunakan.",
  imageOnlyPdf: "Buat PDF gambar saja",
  privacyOcr: "Gambar halaman tidak diunggah untuk OCR.",
};

const fil: ProScanCopy = {
  liveCamera: "Smart camera",
  cameraStarting: "Inihahanda ang camera…",
  cameraDenied: "Hindi magamit ang camera.",
  cameraFallback: "Gamitin ang camera ng device",
  closeCamera: "Isara ang camera",
  manualCapture: "Kunan ngayon",
  autoCaptureOn: "Naka-on ang auto capture",
  autoCaptureOff: "Naka-off ang auto capture",
  holdSteady: "Panatilihing steady",
  moveCloser: "Lumapit sa dokumento",
  moreLight: "Dagdagan ang ilaw",
  tooBright: "Bawasan ang ilaw",
  reduceGlare: "Ikiling nang kaunti para mabawasan ang glare",
  blurry: "Huwag gumalaw para luminaw",
  ready: "Handa nang kumuha",
  quality: "Kalidad ng kuha",
  searchablePdf: "Searchable PDF (OCR)",
  searchableHelp: "Kilalanin ang teksto sa device at magdagdag ng nakatagong searchable layer.",
  ocrPreparing: "Inihahanda ang on-device OCR…",
  ocrRecognizing: "Kinikilala ang teksto…",
  ocrFailed: "Nabigo ang text recognition. Ligtas pa rin ang scan sa device na ito.",
  ocrNetwork: "Dina-download ang OCR engine at language model sa unang paggamit.",
  imageOnlyPdf: "Gumawa ng image-only PDF",
  privacyOcr: "Hindi ina-upload ang page images para sa OCR.",
};

const vi: ProScanCopy = {
  liveCamera: "Máy ảnh thông minh",
  cameraStarting: "Đang khởi động máy ảnh…",
  cameraDenied: "Không thể truy cập máy ảnh.",
  cameraFallback: "Dùng máy ảnh của thiết bị",
  closeCamera: "Đóng máy ảnh",
  manualCapture: "Chụp ngay",
  autoCaptureOn: "Tự động chụp đang bật",
  autoCaptureOff: "Tự động chụp đang tắt",
  holdSteady: "Giữ yên",
  moveCloser: "Đưa máy gần tài liệu hơn",
  moreLight: "Tăng ánh sáng",
  tooBright: "Giảm ánh sáng",
  reduceGlare: "Nghiêng nhẹ để giảm chói",
  blurry: "Giữ yên để ảnh rõ hơn",
  ready: "Sẵn sàng chụp",
  quality: "Chất lượng chụp",
  searchablePdf: "PDF có thể tìm kiếm (OCR)",
  searchableHelp: "Nhận dạng văn bản trên thiết bị và thêm lớp văn bản ẩn có thể tìm kiếm.",
  ocrPreparing: "Đang chuẩn bị OCR trên thiết bị…",
  ocrRecognizing: "Đang nhận dạng văn bản…",
  ocrFailed: "Nhận dạng văn bản thất bại. Bản quét vẫn an toàn trên thiết bị này.",
  ocrNetwork: "Công cụ OCR và mô hình ngôn ngữ được tải xuống khi dùng lần đầu.",
  imageOnlyPdf: "Tạo PDF chỉ có hình ảnh",
  privacyOcr: "Ảnh trang không được tải lên để OCR.",
};

const th: ProScanCopy = {
  liveCamera: "กล้องอัจฉริยะ",
  cameraStarting: "กำลังเปิดกล้อง…",
  cameraDenied: "ไม่สามารถเข้าถึงกล้องได้",
  cameraFallback: "ใช้กล้องของอุปกรณ์แทน",
  closeCamera: "ปิดกล้อง",
  manualCapture: "ถ่ายตอนนี้",
  autoCaptureOn: "เปิดถ่ายอัตโนมัติ",
  autoCaptureOff: "ปิดถ่ายอัตโนมัติ",
  holdSteady: "ถือให้นิ่ง",
  moveCloser: "ขยับเข้าใกล้เอกสาร",
  moreLight: "เพิ่มแสง",
  tooBright: "ลดแสง",
  reduceGlare: "เอียงเล็กน้อยเพื่อลดแสงสะท้อน",
  blurry: "ถือให้นิ่งเพื่อภาพที่คมชัด",
  ready: "พร้อมถ่าย",
  quality: "คุณภาพการถ่าย",
  searchablePdf: "PDF ที่ค้นหาได้ (OCR)",
  searchableHelp: "รู้จำข้อความบนอุปกรณ์และเพิ่มชั้นข้อความที่มองไม่เห็นสำหรับการค้นหา",
  ocrPreparing: "กำลังเตรียม OCR บนอุปกรณ์…",
  ocrRecognizing: "กำลังรู้จำข้อความ…",
  ocrFailed: "รู้จำข้อความไม่สำเร็จ ภาพสแกนยังคงปลอดภัยบนอุปกรณ์นี้",
  ocrNetwork: "ระบบ OCR และโมเดลภาษาจะดาวน์โหลดเมื่อใช้ครั้งแรก",
  imageOnlyPdf: "สร้าง PDF เฉพาะภาพ",
  privacyOcr: "ไม่มีการอัปโหลดภาพหน้าเอกสารเพื่อ OCR",
};

const ne: ProScanCopy = {
  liveCamera: "स्मार्ट क्यामेरा",
  cameraStarting: "क्यामेरा सुरु गर्दै…",
  cameraDenied: "क्यामेरा पहुँच उपलब्ध छैन।",
  cameraFallback: "उपकरणको क्यामेरा प्रयोग गर्नुहोस्",
  closeCamera: "क्यामेरा बन्द गर्नुहोस्",
  manualCapture: "अहिले खिच्नुहोस्",
  autoCaptureOn: "स्वतः खिच्ने चालु",
  autoCaptureOff: "स्वतः खिच्ने बन्द",
  holdSteady: "स्थिर राख्नुहोस्",
  moveCloser: "कागजात नजिक जानुहोस्",
  moreLight: "थप प्रकाश दिनुहोस्",
  tooBright: "प्रकाश घटाउनुहोस्",
  reduceGlare: "चमक घटाउन अलि ढल्काउनुहोस्",
  blurry: "स्पष्ट स्क्यानका लागि स्थिर राख्नुहोस्",
  ready: "खिच्न तयार",
  quality: "क्याप्चर गुणस्तर",
  searchablePdf: "खोज्न मिल्ने PDF (OCR)",
  searchableHelp: "यही उपकरणमा पाठ पहिचान गरी अदृश्य खोजयोग्य तह थपिन्छ।",
  ocrPreparing: "उपकरणमै OCR तयार गर्दै…",
  ocrRecognizing: "पाठ पहिचान गर्दै…",
  ocrFailed: "पाठ पहिचान असफल भयो। स्क्यान यस उपकरणमै सुरक्षित छ।",
  ocrNetwork: "OCR इन्जिन र भाषा मोडेल पहिलो प्रयोगमा डाउनलोड हुन्छ।",
  imageOnlyPdf: "चित्र-मात्र PDF बनाउनुहोस्",
  privacyOcr: "OCR का लागि पृष्ठका तस्बिर अपलोड गरिँदैनन्।",
};

const km: ProScanCopy = {
  liveCamera: "កាមេរ៉ាឆ្លាតវៃ",
  cameraStarting: "កំពុងបើកកាមេរ៉ា…",
  cameraDenied: "មិនអាចចូលប្រើកាមេរ៉ាបានទេ។",
  cameraFallback: "ប្រើកាមេរ៉ារបស់ឧបករណ៍",
  closeCamera: "បិទកាមេរ៉ា",
  manualCapture: "ថតឥឡូវ",
  autoCaptureOn: "បើកថតស្វ័យប្រវត្តិ",
  autoCaptureOff: "បិទថតស្វ័យប្រវត្តិ",
  holdSteady: "កាន់ឱ្យនឹង",
  moveCloser: "ផ្លាស់ទៅជិតឯកសារ",
  moreLight: "បន្ថែមពន្លឺ",
  tooBright: "បន្ថយពន្លឺ",
  reduceGlare: "បង្វិលបន្តិចដើម្បីកាត់បន្ថយចំណាំង",
  blurry: "កាន់ឱ្យនឹងដើម្បីឱ្យច្បាស់",
  ready: "រួចរាល់សម្រាប់ថត",
  quality: "គុណភាពការថត",
  searchablePdf: "PDF អាចស្វែងរកបាន (OCR)",
  searchableHelp: "ស្គាល់អក្សរនៅលើឧបករណ៍នេះ ហើយបន្ថែមស្រទាប់អក្សរលាក់សម្រាប់ស្វែងរក។",
  ocrPreparing: "កំពុងរៀបចំ OCR លើឧបករណ៍…",
  ocrRecognizing: "កំពុងស្គាល់អក្សរ…",
  ocrFailed: "ការស្គាល់អក្សរបរាជ័យ។ ស្កេននៅតែមានសុវត្ថិភាពលើឧបករណ៍នេះ។",
  ocrNetwork: "ម៉ាស៊ីន OCR និងម៉ូដែលភាសាត្រូវបានទាញយកពេលប្រើលើកដំបូង។",
  imageOnlyPdf: "បង្កើត PDF រូបភាពប៉ុណ្ណោះ",
  privacyOcr: "រូបភាពទំព័រមិនត្រូវបានបង្ហោះសម្រាប់ OCR ទេ។",
};

const ar: ProScanCopy = {
  liveCamera: "كاميرا ذكية",
  cameraStarting: "جارٍ تشغيل الكاميرا…",
  cameraDenied: "تعذر الوصول إلى الكاميرا.",
  cameraFallback: "استخدام كاميرا الجهاز",
  closeCamera: "إغلاق الكاميرا",
  manualCapture: "التقاط الآن",
  autoCaptureOn: "الالتقاط التلقائي مفعّل",
  autoCaptureOff: "الالتقاط التلقائي متوقف",
  holdSteady: "ثبّت الجهاز",
  moveCloser: "اقترب من المستند",
  moreLight: "أضف مزيدًا من الضوء",
  tooBright: "خفف الإضاءة",
  reduceGlare: "أمل الجهاز قليلًا لتقليل الوهج",
  blurry: "ثبّت الجهاز للحصول على مسح أوضح",
  ready: "جاهز للالتقاط",
  quality: "جودة الالتقاط",
  searchablePdf: "PDF قابل للبحث (OCR)",
  searchableHelp: "تعرّف على النص على هذا الجهاز وأضف طبقة نص مخفية قابلة للبحث.",
  ocrPreparing: "جارٍ إعداد OCR على الجهاز…",
  ocrRecognizing: "جارٍ التعرّف على النص…",
  ocrFailed: "فشل التعرّف على النص. يظل المسح آمنًا على هذا الجهاز.",
  ocrNetwork: "يتم تنزيل محرك OCR ونموذج اللغة عند أول استخدام.",
  imageOnlyPdf: "إنشاء PDF صور فقط",
  privacyOcr: "لا يتم رفع صور الصفحات لإجراء OCR.",
};

const ru: ProScanCopy = {
  liveCamera: "Умная камера",
  cameraStarting: "Запуск камеры…",
  cameraDenied: "Нет доступа к камере.",
  cameraFallback: "Использовать камеру устройства",
  closeCamera: "Закрыть камеру",
  manualCapture: "Снять сейчас",
  autoCaptureOn: "Автосъёмка включена",
  autoCaptureOff: "Автосъёмка выключена",
  holdSteady: "Держите неподвижно",
  moveCloser: "Поднесите камеру ближе",
  moreLight: "Добавьте света",
  tooBright: "Уменьшите освещение",
  reduceGlare: "Слегка наклоните, чтобы убрать блики",
  blurry: "Держите неподвижно для резкого снимка",
  ready: "Готово к съёмке",
  quality: "Качество снимка",
  searchablePdf: "PDF с поиском (OCR)",
  searchableHelp: "Распознать текст на устройстве и добавить невидимый поисковый слой.",
  ocrPreparing: "Подготовка OCR на устройстве…",
  ocrRecognizing: "Распознавание текста…",
  ocrFailed: "Распознавание не удалось. Скан остаётся безопасно на этом устройстве.",
  ocrNetwork: "Движок OCR и языковая модель загружаются при первом использовании.",
  imageOnlyPdf: "Создать PDF только с изображениями",
  privacyOcr: "Изображения страниц не загружаются для OCR.",
};

const mn: ProScanCopy = {
  liveCamera: "Ухаалаг камер",
  cameraStarting: "Камер асааж байна…",
  cameraDenied: "Камерт хандах боломжгүй байна.",
  cameraFallback: "Төхөөрөмжийн камер ашиглах",
  closeCamera: "Камер хаах",
  manualCapture: "Одоо авах",
  autoCaptureOn: "Автомат зураг авалт асаалттай",
  autoCaptureOff: "Автомат зураг авалт унтраалттай",
  holdSteady: "Тогтвортой барина уу",
  moveCloser: "Баримтад ойртуулна уу",
  moreLight: "Гэрэл нэмнэ үү",
  tooBright: "Гэрлийг багасгана уу",
  reduceGlare: "Гялбааг багасгахын тулд бага зэрэг хазайлгаарай",
  blurry: "Илүү тод авахын тулд хөдөлгөөнгүй барина уу",
  ready: "Зураг авахад бэлэн",
  quality: "Зургийн чанар",
  searchablePdf: "Хайлттай PDF (OCR)",
  searchableHelp: "Энэ төхөөрөмж дээр текст таньж, үл үзэгдэх хайлтын давхарга нэмнэ.",
  ocrPreparing: "Төхөөрөмжийн OCR бэлдэж байна…",
  ocrRecognizing: "Текст таньж байна…",
  ocrFailed: "Текст танилт амжилтгүй. Скан энэ төхөөрөмж дээр аюулгүй хэвээр байна.",
  ocrNetwork: "OCR хөдөлгүүр ба хэлний загвар анхны хэрэглээнд татагдана.",
  imageOnlyPdf: "Зөвхөн зурагтай PDF үүсгэх",
  privacyOcr: "OCR-д хуудасны зургуудыг серверт илгээхгүй.",
};

const uk: ProScanCopy = {
  liveCamera: "Розумна камера",
  cameraStarting: "Запуск камери…",
  cameraDenied: "Немає доступу до камери.",
  cameraFallback: "Скористатися камерою пристрою",
  closeCamera: "Закрити камеру",
  manualCapture: "Зняти зараз",
  autoCaptureOn: "Автозйомку ввімкнено",
  autoCaptureOff: "Автозйомку вимкнено",
  holdSteady: "Тримайте нерухомо",
  moveCloser: "Наблизьтеся до документа",
  moreLight: "Додайте освітлення",
  tooBright: "Зменште освітлення",
  reduceGlare: "Трохи нахиліть, щоб зменшити відблиск",
  blurry: "Тримайте нерухомо для чіткішого скану",
  ready: "Готово до зйомки",
  quality: "Якість зйомки",
  searchablePdf: "PDF з пошуком (OCR)",
  searchableHelp: "Розпізнати текст на пристрої та додати невидимий пошуковий шар.",
  ocrPreparing: "Підготовка OCR на пристрої…",
  ocrRecognizing: "Розпізнавання тексту…",
  ocrFailed: "Не вдалося розпізнати текст. Скан залишається безпечно на цьому пристрої.",
  ocrNetwork: "Модуль OCR і мовна модель завантажуються під час першого використання.",
  imageOnlyPdf: "Створити PDF лише із зображень",
  privacyOcr: "Зображення сторінок не завантажуються для OCR.",
};

const COPY: Record<SupportedLocale, ProScanCopy> = {
  en,
  ko,
  "zh-CN": zhCN,
  id,
  fil,
  vi,
  th,
  ne,
  km,
  ar,
  ru,
  mn,
  uk,
};

export function proScanCopy(locale: SupportedLocale): ProScanCopy {
  return COPY[locale];
}
