import type { SupportedLocale } from "@print-cess/i18n";

const en = {
  title: "Scan a document",
  intro: "Photograph each page. The PDF is made only on this device.",
  camera: "Scan with camera",
  gallery: "Add from photos",
  empty: "Lay the page flat in good light and hold the camera directly above it.",
  pages: "{{count}} of 10 pages",
  addPage: "Add another page",
  enhance: "Make text clearer in black and white",
  rotate: "Rotate",
  moveEarlier: "Move earlier",
  moveLater: "Move later",
  remove: "Remove",
  makePdf: "Make PDF",
  making: "Making your PDF…",
  back: "Back",
  done: "Your scan is ready",
  private: "The photos and PDF stay on this device unless you choose to share them.",
  share: "Send to another device",
  download: "Download PDF",
  print: "Print now",
  scanAgain: "Scan again",
  shareFallback: "File sharing is not available here. The PDF was downloaded instead.",
  downloaded: "PDF download started.",
  printHint: "Choose a printer in your device's print window.",
  tooMany: "You can scan up to 10 pages at once.",
  imageError: "One of those photos could not be opened. Try taking it again.",
  genericError: "The PDF could not be made. Try again.",
  scannedFile: "Print-cess-scan.pdf",
  useForPrint: "Use this PDF",
  closeScanner: "Cancel scanning",
};

const ko: typeof en = {
  title: "문서 스캔",
  intro: "페이지를 한 장씩 촬영하세요. PDF는 이 기기 안에서만 만들어져요.",
  camera: "카메라로 스캔",
  gallery: "사진에서 추가",
  empty: "문서를 밝고 평평한 곳에 놓고 카메라를 바로 위에서 비춰주세요.",
  pages: "{{count}} / 10페이지",
  addPage: "페이지 더 추가",
  enhance: "흑백으로 글자를 더 선명하게",
  rotate: "회전",
  moveEarlier: "앞으로 이동",
  moveLater: "뒤로 이동",
  remove: "삭제",
  makePdf: "PDF 만들기",
  making: "PDF를 만들고 있어요…",
  back: "뒤로",
  done: "스캔한 문서가 준비됐어요",
  private: "공유를 선택하기 전까지 사진과 PDF는 이 기기 안에만 있어요.",
  share: "다른 기기로 전송",
  download: "PDF 다운로드",
  print: "즉시 출력",
  scanAgain: "다시 스캔",
  shareFallback: "이 브라우저에서는 파일 공유를 열 수 없어 PDF를 다운로드했어요.",
  downloaded: "PDF 다운로드를 시작했어요.",
  printHint: "기기의 인쇄 창에서 프린터를 선택하세요.",
  tooMany: "한 번에 최대 10페이지까지 스캔할 수 있어요.",
  imageError: "사진 한 장을 열 수 없어요. 다시 촬영해 주세요.",
  genericError: "PDF를 만들지 못했어요. 다시 시도해 주세요.",
  scannedFile: "Print-cess-스캔.pdf",
  useForPrint: "이 PDF로 인쇄",
  closeScanner: "스캔 취소",
};

const zhCN: typeof en = {
  title: "扫描文档",
  intro: "逐页拍照。PDF 只会在此设备上生成。",
  camera: "用相机扫描",
  gallery: "从照片添加",
  empty: "请将页面平放在光线充足处，并让相机从正上方拍摄。",
  pages: "已添加 {{count}} / 10 页",
  addPage: "再添加一页",
  enhance: "转为黑白并增强文字清晰度",
  rotate: "旋转",
  moveEarlier: "向前移动",
  moveLater: "向后移动",
  remove: "删除",
  makePdf: "生成 PDF",
  making: "正在生成 PDF…",
  back: "返回",
  done: "扫描文档已准备好",
  private: "除非您主动分享，否则照片和 PDF 只保存在此设备上。",
  share: "发送到其他设备",
  download: "下载 PDF",
  print: "立即打印",
  scanAgain: "重新扫描",
  shareFallback: "此处无法使用文件共享，已改为下载 PDF。",
  downloaded: "PDF 已开始下载。",
  printHint: "请在设备的打印窗口中选择打印机。",
  tooMany: "一次最多可扫描 10 页。",
  imageError: "有一张照片无法打开，请重新拍摄。",
  genericError: "无法生成 PDF，请重试。",
  scannedFile: "Print-cess-扫描.pdf",
  useForPrint: "使用此 PDF",
  closeScanner: "取消扫描",
};

const id: typeof en = {
  title: "Pindai dokumen",
  intro: "Foto setiap halaman. PDF dibuat hanya di perangkat ini.",
  camera: "Pindai dengan kamera",
  gallery: "Tambah dari foto",
  empty: "Letakkan halaman rata di tempat terang dan arahkan kamera tepat dari atas.",
  pages: "{{count}} dari 10 halaman",
  addPage: "Tambah halaman lagi",
  enhance: "Perjelas teks dalam hitam putih",
  rotate: "Putar",
  moveEarlier: "Pindahkan ke depan",
  moveLater: "Pindahkan ke belakang",
  remove: "Hapus",
  makePdf: "Buat PDF",
  making: "Membuat PDF…",
  back: "Kembali",
  done: "Hasil pindai siap",
  private: "Foto dan PDF tetap di perangkat ini kecuali Anda memilih untuk membagikannya.",
  share: "Kirim ke perangkat lain",
  download: "Unduh PDF",
  print: "Cetak sekarang",
  scanAgain: "Pindai lagi",
  shareFallback: "Berbagi file tidak tersedia di sini. PDF diunduh sebagai gantinya.",
  downloaded: "Pengunduhan PDF dimulai.",
  printHint: "Pilih printer di jendela cetak perangkat Anda.",
  tooMany: "Anda dapat memindai hingga 10 halaman sekaligus.",
  imageError: "Salah satu foto tidak dapat dibuka. Coba ambil foto lagi.",
  genericError: "PDF tidak dapat dibuat. Coba lagi.",
  scannedFile: "Print-cess-scan.pdf",
  useForPrint: "Gunakan PDF ini",
  closeScanner: "Batalkan pemindaian",
};

const fil: typeof en = {
  title: "Mag-scan ng dokumento",
  intro: "Kunan ng larawan ang bawat pahina. Sa device na ito lang gagawin ang PDF.",
  camera: "Mag-scan gamit ang camera",
  gallery: "Magdagdag mula sa mga larawan",
  empty: "Ilatag nang patag ang pahina sa maliwanag na lugar at itapat ang camera mula sa itaas.",
  pages: "{{count}} sa 10 pahina",
  addPage: "Magdagdag pa ng pahina",
  enhance: "Linawin ang teksto sa itim at puti",
  rotate: "I-rotate",
  moveEarlier: "Ilipat pauna",
  moveLater: "Ilipat pahuli",
  remove: "Alisin",
  makePdf: "Gumawa ng PDF",
  making: "Ginagawa ang PDF…",
  back: "Bumalik",
  done: "Handa na ang na-scan na dokumento",
  private: "Mananatili sa device na ito ang mga larawan at PDF maliban kung ibabahagi mo ang mga ito.",
  share: "Ipadala sa ibang device",
  download: "I-download ang PDF",
  print: "I-print ngayon",
  scanAgain: "Mag-scan ulit",
  shareFallback: "Hindi available dito ang pagbabahagi ng file. Na-download na lang ang PDF.",
  downloaded: "Nagsimula na ang pag-download ng PDF.",
  printHint: "Pumili ng printer sa print window ng iyong device.",
  tooMany: "Hanggang 10 pahina ang maaaring i-scan nang sabay.",
  imageError: "Hindi mabuksan ang isa sa mga larawan. Subukang kunan ulit.",
  genericError: "Hindi nagawa ang PDF. Subukan ulit.",
  scannedFile: "Print-cess-scan.pdf",
  useForPrint: "Gamitin ang PDF na ito",
  closeScanner: "Kanselahin ang pag-scan",
};

const vi: typeof en = {
  title: "Quét tài liệu",
  intro: "Chụp từng trang. PDF chỉ được tạo trên thiết bị này.",
  camera: "Quét bằng camera",
  gallery: "Thêm từ ảnh",
  empty: "Đặt trang giấy phẳng ở nơi đủ sáng và giữ camera ngay phía trên.",
  pages: "{{count}} / 10 trang",
  addPage: "Thêm trang khác",
  enhance: "Làm chữ rõ hơn ở chế độ đen trắng",
  rotate: "Xoay",
  moveEarlier: "Chuyển lên trước",
  moveLater: "Chuyển xuống sau",
  remove: "Xóa",
  makePdf: "Tạo PDF",
  making: "Đang tạo PDF…",
  back: "Quay lại",
  done: "Bản quét đã sẵn sàng",
  private: "Ảnh và PDF chỉ ở trên thiết bị này trừ khi bạn chọn chia sẻ.",
  share: "Gửi sang thiết bị khác",
  download: "Tải PDF",
  print: "In ngay",
  scanAgain: "Quét lại",
  shareFallback: "Không thể chia sẻ tệp tại đây. PDF đã được tải xuống thay thế.",
  downloaded: "Đã bắt đầu tải PDF.",
  printHint: "Chọn máy in trong cửa sổ in của thiết bị.",
  tooMany: "Bạn có thể quét tối đa 10 trang cùng lúc.",
  imageError: "Không mở được một ảnh. Hãy chụp lại ảnh đó.",
  genericError: "Không thể tạo PDF. Hãy thử lại.",
  scannedFile: "Print-cess-scan.pdf",
  useForPrint: "Dùng PDF này",
  closeScanner: "Hủy quét",
};

const th: typeof en = {
  title: "สแกนเอกสาร",
  intro: "ถ่ายภาพทีละหน้า PDF จะถูกสร้างบนอุปกรณ์นี้เท่านั้น",
  camera: "สแกนด้วยกล้อง",
  gallery: "เพิ่มจากรูปภาพ",
  empty: "วางเอกสารให้ราบในที่สว่าง และถือกล้องให้อยู่ตรงเหนือเอกสาร",
  pages: "{{count}} จาก 10 หน้า",
  addPage: "เพิ่มหน้าอื่น",
  enhance: "ทำให้ตัวอักษรชัดขึ้นแบบขาวดำ",
  rotate: "หมุน",
  moveEarlier: "เลื่อนไปข้างหน้า",
  moveLater: "เลื่อนไปข้างหลัง",
  remove: "ลบ",
  makePdf: "สร้าง PDF",
  making: "กำลังสร้าง PDF…",
  back: "กลับ",
  done: "เอกสารที่สแกนพร้อมแล้ว",
  private: "รูปภาพและ PDF จะอยู่บนอุปกรณ์นี้ เว้นแต่คุณเลือกแชร์",
  share: "ส่งไปยังอุปกรณ์อื่น",
  download: "ดาวน์โหลด PDF",
  print: "พิมพ์ตอนนี้",
  scanAgain: "สแกนอีกครั้ง",
  shareFallback: "ไม่สามารถแชร์ไฟล์ได้ที่นี่ จึงดาวน์โหลด PDF แทน",
  downloaded: "เริ่มดาวน์โหลด PDF แล้ว",
  printHint: "เลือกเครื่องพิมพ์ในหน้าต่างพิมพ์ของอุปกรณ์",
  tooMany: "สแกนได้สูงสุด 10 หน้าต่อครั้ง",
  imageError: "เปิดรูปภาพหนึ่งรูปไม่ได้ โปรดลองถ่ายใหม่",
  genericError: "สร้าง PDF ไม่สำเร็จ โปรดลองอีกครั้ง",
  scannedFile: "Print-cess-scan.pdf",
  useForPrint: "ใช้ PDF นี้",
  closeScanner: "ยกเลิกการสแกน",
};

const ne: typeof en = {
  title: "कागजात स्क्यान गर्नुहोस्",
  intro: "हरेक पृष्ठको फोटो खिच्नुहोस्। PDF यही उपकरणमा मात्र बनाइन्छ।",
  camera: "क्यामेराले स्क्यान गर्नुहोस्",
  gallery: "फोटोबाट थप्नुहोस्",
  empty: "पृष्ठलाई उज्यालो ठाउँमा समतल राखेर क्यामेरा ठीक माथिबाट राख्नुहोस्।",
  pages: "१० मध्ये {{count}} पृष्ठ",
  addPage: "अर्को पृष्ठ थप्नुहोस्",
  enhance: "कालो-सेतोमा अक्षर अझ स्पष्ट बनाउनुहोस्",
  rotate: "घुमाउनुहोस्",
  moveEarlier: "अगाडि सार्नुहोस्",
  moveLater: "पछि सार्नुहोस्",
  remove: "हटाउनुहोस्",
  makePdf: "PDF बनाउनुहोस्",
  making: "PDF बनाउँदै…",
  back: "पछाडि",
  done: "स्क्यान तयार छ",
  private: "तपाईंले साझा नगरेसम्म फोटो र PDF यही उपकरणमा रहन्छन्।",
  share: "अर्को उपकरणमा पठाउनुहोस्",
  download: "PDF डाउनलोड गर्नुहोस्",
  print: "अहिले प्रिन्ट गर्नुहोस्",
  scanAgain: "फेरि स्क्यान गर्नुहोस्",
  shareFallback: "यहाँ फाइल साझा गर्न मिलेन। यसको सट्टा PDF डाउनलोड गरियो।",
  downloaded: "PDF डाउनलोड सुरु भयो।",
  printHint: "उपकरणको प्रिन्ट विन्डोमा प्रिन्टर छान्नुहोस्।",
  tooMany: "एकपटकमा बढीमा १० पृष्ठ स्क्यान गर्न सकिन्छ।",
  imageError: "एउटा फोटो खोल्न सकिएन। फेरि फोटो खिच्नुहोस्।",
  genericError: "PDF बनाउन सकिएन। फेरि प्रयास गर्नुहोस्।",
  scannedFile: "Print-cess-scan.pdf",
  useForPrint: "यो PDF प्रयोग गर्नुहोस्",
  closeScanner: "स्क्यान रद्द गर्नुहोस्",
};

const km: typeof en = {
  title: "ស្កេនឯកសារ",
  intro: "ថតរូបមួយទំព័រម្តង។ PDF ត្រូវបានបង្កើតតែនៅលើឧបករណ៍នេះ។",
  camera: "ស្កេនដោយកាមេរ៉ា",
  gallery: "បន្ថែមពីរូបថត",
  empty: "ដាក់ឯកសារឲ្យរាបស្មើនៅកន្លែងមានពន្លឺល្អ ហើយកាន់កាមេរ៉ាត្រង់ពីលើ។",
  pages: "{{count}} ក្នុងចំណោម 10 ទំព័រ",
  addPage: "បន្ថែមទំព័រមួយទៀត",
  enhance: "ធ្វើឲ្យអក្សរច្បាស់ជាងមុនជាពណ៌ខ្មៅស",
  rotate: "បង្វិល",
  moveEarlier: "ផ្លាស់ទីទៅមុខ",
  moveLater: "ផ្លាស់ទីទៅក្រោយ",
  remove: "លុប",
  makePdf: "បង្កើត PDF",
  making: "កំពុងបង្កើត PDF…",
  back: "ត្រឡប់ក្រោយ",
  done: "ឯកសារស្កេនរួចរាល់",
  private: "រូបថត និង PDF នឹងស្ថិតនៅលើឧបករណ៍នេះ លុះត្រាតែអ្នកជ្រើសរើសចែករំលែក។",
  share: "ផ្ញើទៅឧបករណ៍ផ្សេង",
  download: "ទាញយក PDF",
  print: "បោះពុម្ពឥឡូវនេះ",
  scanAgain: "ស្កេនម្តងទៀត",
  shareFallback: "មិនអាចចែករំលែកឯកសារនៅទីនេះបានទេ។ PDF ត្រូវបានទាញយកជំនួស។",
  downloaded: "បានចាប់ផ្តើមទាញយក PDF។",
  printHint: "ជ្រើសរើសម៉ាស៊ីនបោះពុម្ពក្នុងផ្ទាំងបោះពុម្ពរបស់ឧបករណ៍។",
  tooMany: "អាចស្កេនបានអតិបរមា 10 ទំព័រក្នុងមួយដង។",
  imageError: "មិនអាចបើករូបថតមួយបានទេ។ សូមថតម្តងទៀត។",
  genericError: "មិនអាចបង្កើត PDF បានទេ។ សូមព្យាយាមម្តងទៀត។",
  scannedFile: "Print-cess-scan.pdf",
  useForPrint: "ប្រើ PDF នេះ",
  closeScanner: "បោះបង់ការស្កេន",
};

const ar: typeof en = {
  title: "مسح مستند",
  intro: "صوّر كل صفحة. يتم إنشاء ملف PDF على هذا الجهاز فقط.",
  camera: "المسح بالكاميرا",
  gallery: "إضافة من الصور",
  empty: "ضع الصفحة بشكل مستو في إضاءة جيدة وأمسك الكاميرا فوقها مباشرة.",
  pages: "{{count}} من 10 صفحات",
  addPage: "إضافة صفحة أخرى",
  enhance: "توضيح النص بالأبيض والأسود",
  rotate: "تدوير",
  moveEarlier: "نقل إلى الأمام",
  moveLater: "نقل إلى الخلف",
  remove: "إزالة",
  makePdf: "إنشاء PDF",
  making: "جارٍ إنشاء PDF…",
  back: "رجوع",
  done: "المسح جاهز",
  private: "تبقى الصور وملف PDF على هذا الجهاز ما لم تختر مشاركتها.",
  share: "إرسال إلى جهاز آخر",
  download: "تنزيل PDF",
  print: "طباعة الآن",
  scanAgain: "المسح مرة أخرى",
  shareFallback: "مشاركة الملفات غير متاحة هنا. تم تنزيل ملف PDF بدلاً من ذلك.",
  downloaded: "بدأ تنزيل ملف PDF.",
  printHint: "اختر طابعة من نافذة الطباعة على جهازك.",
  tooMany: "يمكنك مسح ما يصل إلى 10 صفحات في المرة الواحدة.",
  imageError: "تعذر فتح إحدى الصور. حاول التقاطها مرة أخرى.",
  genericError: "تعذر إنشاء ملف PDF. حاول مرة أخرى.",
  scannedFile: "Print-cess-scan.pdf",
  useForPrint: "استخدام ملف PDF هذا",
  closeScanner: "إلغاء المسح",
};

const ru: typeof en = {
  title: "Сканировать документ",
  intro: "Сфотографируйте каждую страницу. PDF создается только на этом устройстве.",
  camera: "Сканировать камерой",
  gallery: "Добавить из фото",
  empty: "Положите страницу ровно при хорошем освещении и держите камеру прямо над ней.",
  pages: "{{count}} из 10 страниц",
  addPage: "Добавить страницу",
  enhance: "Сделать текст четче в черно-белом режиме",
  rotate: "Повернуть",
  moveEarlier: "Переместить вперед",
  moveLater: "Переместить назад",
  remove: "Удалить",
  makePdf: "Создать PDF",
  making: "Создаем PDF…",
  back: "Назад",
  done: "Скан готов",
  private: "Фотографии и PDF остаются на этом устройстве, пока вы не решите ими поделиться.",
  share: "Отправить на другое устройство",
  download: "Скачать PDF",
  print: "Печать сейчас",
  scanAgain: "Сканировать снова",
  shareFallback: "Обмен файлами здесь недоступен. Вместо этого PDF был скачан.",
  downloaded: "Загрузка PDF началась.",
  printHint: "Выберите принтер в окне печати вашего устройства.",
  tooMany: "За один раз можно отсканировать до 10 страниц.",
  imageError: "Не удалось открыть одну из фотографий. Сделайте снимок еще раз.",
  genericError: "Не удалось создать PDF. Попробуйте еще раз.",
  scannedFile: "Print-cess-scan.pdf",
  useForPrint: "Использовать этот PDF",
  closeScanner: "Отменить сканирование",
};

const mn: typeof en = {
  title: "Баримт скан хийх",
  intro: "Хуудас бүрийн зургийг авна уу. PDF зөвхөн энэ төхөөрөмж дээр үүснэ.",
  camera: "Камераар скан хийх",
  gallery: "Зургаас нэмэх",
  empty: "Хуудсыг гэрэл сайтай газар тэгш тавиад камерыг яг дээрээс нь барина уу.",
  pages: "10 хуудаснаас {{count}}",
  addPage: "Дахин хуудас нэмэх",
  enhance: "Хар цагаанаар бичвэрийг тодруулах",
  rotate: "Эргүүлэх",
  moveEarlier: "Урагш зөөх",
  moveLater: "Хойш зөөх",
  remove: "Устгах",
  makePdf: "PDF үүсгэх",
  making: "PDF үүсгэж байна…",
  back: "Буцах",
  done: "Скан бэлэн боллоо",
  private: "Та хуваалцахаар сонгох хүртэл зураг болон PDF энэ төхөөрөмж дээр үлдэнэ.",
  share: "Өөр төхөөрөмж рүү илгээх",
  download: "PDF татах",
  print: "Одоо хэвлэх",
  scanAgain: "Дахин скан хийх",
  shareFallback: "Энд файл хуваалцах боломжгүй тул PDF-г татлаа.",
  downloaded: "PDF таталт эхэллээ.",
  printHint: "Төхөөрөмжийн хэвлэх цонхноос принтерээ сонгоно уу.",
  tooMany: "Нэг удаад 10 хүртэл хуудас скан хийж болно.",
  imageError: "Нэг зураг нээгдсэнгүй. Дахин зураг авна уу.",
  genericError: "PDF үүсгэж чадсангүй. Дахин оролдоно уу.",
  scannedFile: "Print-cess-scan.pdf",
  useForPrint: "Энэ PDF-г ашиглах",
  closeScanner: "Сканыг цуцлах",
};

const uk: typeof en = {
  title: "Сканувати документ",
  intro: "Сфотографуйте кожну сторінку. PDF створюється лише на цьому пристрої.",
  camera: "Сканувати камерою",
  gallery: "Додати з фото",
  empty: "Покладіть сторінку рівно при доброму освітленні й тримайте камеру прямо над нею.",
  pages: "{{count}} із 10 сторінок",
  addPage: "Додати ще сторінку",
  enhance: "Зробити текст чіткішим у чорно-білому режимі",
  rotate: "Повернути",
  moveEarlier: "Перемістити вперед",
  moveLater: "Перемістити назад",
  remove: "Видалити",
  makePdf: "Створити PDF",
  making: "Створюємо PDF…",
  back: "Назад",
  done: "Скан готовий",
  private: "Фото та PDF залишаються на цьому пристрої, доки ви не вирішите ними поділитися.",
  share: "Надіслати на інший пристрій",
  download: "Завантажити PDF",
  print: "Друкувати зараз",
  scanAgain: "Сканувати знову",
  shareFallback: "Обмін файлами тут недоступний. Натомість PDF було завантажено.",
  downloaded: "Завантаження PDF розпочато.",
  printHint: "Виберіть принтер у вікні друку вашого пристрою.",
  tooMany: "За один раз можна відсканувати до 10 сторінок.",
  imageError: "Не вдалося відкрити одне з фото. Спробуйте зробити його ще раз.",
  genericError: "Не вдалося створити PDF. Спробуйте ще раз.",
  scannedFile: "Print-cess-scan.pdf",
  useForPrint: "Використати цей PDF",
  closeScanner: "Скасувати сканування",
};

export type ScanCopy = typeof en;

const COPY_BY_LOCALE: Record<SupportedLocale, ScanCopy> = {
  en,
  ko,
  "zh-CN": zhCN,
  id,
  fil,
  vi,
  th,
  ne,
  km,
  ar,
  ru,
  mn,
  uk,
};

export function scanCopy(locale: SupportedLocale): ScanCopy {
  return COPY_BY_LOCALE[locale];
}

export function formatScanCopy(value: string, values: Record<string, string | number>): string {
  return value.replace(/\{\{(\w+)\}\}/gu, (_, key: string) => String(values[key] ?? ""));
}

export const SCAN_HOME_CTA: Record<SupportedLocale, string> = {
  en: "Scan a document",
  ko: "문서 스캔",
  "zh-CN": "扫描文档",
  id: "Pindai dokumen",
  fil: "Mag-scan ng dokumento",
  vi: "Quét tài liệu",
  th: "สแกนเอกสาร",
  ne: "कागजात स्क्यान गर्नुहोस्",
  km: "ស្កេនឯកសារ",
  ar: "مسح مستند",
  ru: "Сканировать документ",
  mn: "Баримт скан хийх",
  uk: "Сканувати документ",
};
